ENCODER_MAP_ENABLE = yes

LTO_ENABLE = yes
VIA_ENABLE = yes
VIAL_ENABLE = yes

KEY_OVERRIDE_ENABLE = no
TAP_DANCE_ENABLE = no

CONSOLE_ENABLE = no
COMMAND_ENABLE = no
MOUSEKEY_ENABLE = no
SPACE_CADET_ENABLE = no
GRAVE_ESC_ENABLE = no
MAGIC_ENABLE = no

QMK_SETTINGS = no
COMBO_ENABLE = no
CAPS_WORD_ENABLE = no
LAYER_LOCK_ENABLE = no
REPEAT_KEY_ENABLE = no
